<?php

/**
 * TrAvatarTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrAvatarTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrAvatarTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrAvatar');
    }
}