<?php

/**
 * TrCityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrCityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrCityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrCity');
    }
}