<?php

/**
 * TrEmailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrEmailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrEmailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrEmail');
    }
}