<?php

/**
 * TrJournalFavouriteListTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrJournalFavouriteListTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrJournalFavouriteListTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrJournalFavouriteList');
    }
}