<?php

/**
 * TrJournalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrJournalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrJournalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrJournal');
    }
}