<?php

/**
 * TrJournalPlaceJournalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrJournalPlaceJournalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrJournalPlaceJournalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrJournalPlaceJournal');
    }
}