<?php

/**
 * TrJournalPlaceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrJournalPlaceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrJournalPlaceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrJournalPlace');
    }
}