<?php

/**
 * TrJournalCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrJournalCommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrJournalCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrJournalComment');
    }
}