<?php

/**
 * TrJournalPlaceFavouriteListTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrJournalPlaceFavouriteListTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrJournalPlaceFavouriteListTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrJournalPlaceFavouriteList');
    }
}