<?php

/**
 * TrJournalMovementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrJournalMovementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrJournalMovementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrJournalMovement');
    }
}