<?php

/**
 * TrJournalPlaceInfoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrJournalPlaceInfoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrJournalPlaceInfoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrJournalPlaceInfo');
    }
}