<?php

/**
 * TrOnlineRecordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrOnlineRecordTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrOnlineRecordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrOnlineRecord');
    }
}