<?php

/**
 * TrPhotoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrPhotoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrPhotoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrPhoto');
    }
}