<?php

/**
 * TrPlaceTagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrPlaceTagTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrPlaceTagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrPlaceTag');
    }
}