<?php

/**
 * TrPlaceHotMonthTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrPlaceHotMonthTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrPlaceHotMonthTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrPlaceHotMonth');
    }
}