<?php

/**
 * TrProvinceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrProvinceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrProvinceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrProvince');
    }
}