<?php

/**
 * TrRegisterEmailInfoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrRegisterEmailInfoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrRegisterEmailInfoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrRegisterEmailInfo');
    }
}