<?php

/**
 * TrRegisterTelephoneInfoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrRegisterTelephoneInfoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrRegisterTelephoneInfoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrRegisterTelephoneInfo');
    }
}