<?php

/**
 * TrSayingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrSayingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrSayingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrSaying');
    }
}