<?php

/**
 * TrSublocalityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrSublocalityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrSublocalityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrSublocality');
    }
}