<?php

/**
 * TrTagTextTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrTagTextTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrTagTextTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrTagText');
    }
}