<?php

/**
 * TrUserMarkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrUserMarkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrUserMarkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrUserMark');
    }
}