<?php

/**
 * TrUserTokenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrUserTokenTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrUserTokenTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrUserToken');
    }
}