<?php

/**
 * TrUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrUser');
    }
}