<?php

/**
 * TrUserToUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrUserToUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrUserToUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrUserToUser');
    }
}