<?php

/**
 * TrUserLocationInfoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrUserLocationInfoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrUserLocationInfoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrUserLocationInfo');
    }
}