<?php

/**
 * TrUserImSettingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrUserImSettingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrUserImSettingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrUserImSetting');
    }
}