<p>.</p><p>.</p><p>.</p><p>.</p>
<center><strong>Welcome to UGShare!!!</strong></center>

<center>
<form action="http://localhost/Journal/public/index.php/login/login" method="post">
	<p> <strong>账号名：</strong> <input name="loginInfo" length="15"/> 邮箱地址、手机号</p>
	<p> <strong>密码：</strong> <input name="password" type="password" length="15"/></p>
	<p><input type="submit"/></p>
</form>
</center>

<?php 

