<p>..</p><p>..</p><p>..</p><p>..</p>
<center>
<form action="http://localhost/Journal/public/index.php/register/register" method="post">
	<p> <strong>注册信息：</strong> <input name="registerInfo" length="15"/>	邮箱地址、手机号</p>
	<p> <strong>用户名：</strong> <input name="username" length="15"/></p>
	<p> <strong>密码：</strong> <input name="password" type="password" length="15"/></p>
	<p><input type="submit"/></p>
</form>
</center>
