<?php
class Models_Behavior_PBehaviorEnum
{
	public function __construct()
	{}
	
	CONST COMMONBHNAME = 'Models_Behavior_';
	//behavior begin	用到 'bh0044'
	//<<<...
	CONST BREGISTEREMAIL 					= 'bh0001';
	CONST BREGISTERTELEPHONE				= 'bh0002';
	CONST BREGISTEROTHERS 					= 'bh0003';
	CONST BREGISTERCONFIRMEMAIL				= 'bh0004';
	CONST BREGISTERCONFIRMTELEPHONEBYMSG	= 'bh0005';
	CONST BREGISTERCONFIRMTELEPHONEBYCODE	= 'bh0037';
	CONST BLOGINEMAIL						= 'bh0006';
	CONST BLOGINTELEPHONE					= 'bh0007';
	CONST BLOGINOTHERS						= 'bh0008';
	CONST BBINDEMAIL						= 'bh0009';
	CONST BBINDMOBILE						= 'bh0010';
	CONST BFOLLOWUSERBYID					= 'bh0011';
	CONST BFOLLOWUSERBYTELEPHONE			= 'bh0036';
	CONST BUNFOLLOWUSERBYID					= 'bh0038';
	CONST BSETAVATAR						= 'bh0012';
	CONST BSETNEWPASSWORD					= 'bh0013';
	CONST BSETSAYING						= 'bh0014';
	
	CONST BADDPLACE							= 'bh0015';
	CONST BDELETEPLACE						= 'bh0016';
	
	CONST BADDJOURNALPLACEINFO				= 'bh0017';
	CONST BADDPHOTOTOJOURNALINFO			= 'bh0018';
	CONST BCOMMENTJOURNAL					= 'bh0019';	
	CONST BCOMMENTJOURNALPLACE				= 'bh0020';
	CONST BCREATEJOURNAL					= 'bh0021';
	CONST BCREATEJOURNALPLACE				= 'bh0022';
	CONST BDELETEJOURNAL					= 'bh0023';
	CONST BDELETEJOURNALPLACE				= 'bh0024';
	CONST BDELETEJOURNALPLACEINFO			= 'bh0041';
	CONST BDELETEINFOPHOTO					= 'bh0042';
	CONST BDELETEJOURNALCOMMENT				= 'bh0043';
	CONST BDELETEJOURNALPLACECOMMENT		= 'bh0044';
	CONST BFAVOURITEJOURNAL					= 'bh0025';
	CONST BFAVOURITEJOURNALPLACE			= 'bh0026';
	CONST BUNFAVOURITEJOURNAL				= 'bh0039';
	CONST BUNFAVOURITEJOURNALPLACE			= 'bh0040';
	CONST BSETJOURNALPRIVACY				= 'bh0027';
	
	CONST BADDBLACKLIST						= 'bh0028';
	CONST BCLEARBLACKLIST					= 'bh0029';
	CONST BDELETEBLACKLIST					= 'bh0030';
	CONST BENABLEIM							= 'bh0031';
	CONST BRECEIVEMSG						= 'bh0032';
	CONST BSENDMSG							= 'bh0033';
	CONST BADDPLACETAG						= 'bh0034';
	CONST BAGREETAG							= 'bh0035';
	//...>>
	//behavior end
	
	//behavior parameter begin
	//<<...
	//REGISTER EMAIL
	CONST PREGISTEREMAIL_EMAIL  				= 'pp0001x01';
	CONST PREGISTEREMAIL_PASSWORD				= 'pp0001x02';
	CONST PREGISTEREMAIL_USERNAME				= 'pp0001x03';
	//REGISTER TELEPHONE
	CONST PREGISTERTELEPHONE_TELEPHONE  		= 'pp0002x01';
	CONST PREGISTERTELEPHONE_PASSWORD			= 'pp0002x02';
	CONST PREGISTERTELEPHONE_USERNAME			= 'pp0002x03';
	//REGISTER OTHERS
	CONST PREGISTEROTHERS_ACCESSTOKEN  			= 'pp0003x01';
	//REGISTER CONFIRM EMAIL
	CONST PREGISTERCONFIRMEMAIL_VERIFYCODE		= 'pp0004X01';
	//REGISTER CONFIRM TELEPHONE BY MSG
	CONST PREGISTERCONFIRMTELEPHONEBYMSG_TELEPHONE		= 'pp0005x01';
	CONST PREGISTERCONFIRMTELEPHONEBYMSG_CONTENT 		= 'pp0005x02';
	//REGISTER CONFIRM TELEPHONE BY VERIFYCODE
	CONST PREGISTERCONFIRMTELEPHONEBYCODE_VERIFYCODE	= 'pp0037x01';
	//LOGIN BY EMAIL
	CONST PLOGINEMAIL_EMAIL						= 'pp0006x01';
	CONST PLOGINEMAIL_PASSWORD					= 'pp0006x02';
	//LOGIN BY TELEPHONE
	CONST PLOGINTELEPHONE_TELEPHONE				= 'pp0007x01';
	CONST PLOGINTELEPHONE_PASSWORD				= 'pp0007x02';
	//LOGIN BY OTHER ACCOUNTS
	
	//BIND THE USER ACCOUNT TO EMAIL
	CONST PBINDEMAIL_USERID						= 'pp0009x01';
	CONST PBINDEMAIL_EMAIL						= 'pp0009x02';
	//BIND THE USER ACCOUNT TO MOBLIE
	CONST PBINDMOBILE_USERID					= 'pp0010x01';
	CONST PBINDMOBILE_MOBILE					= 'pp0010x02';
	//FOLLOW THE USER BY ID
	CONST PFOLLOWUSERBYID_USERID				= 'pp0011x01';
	CONST PFOLLOWUSERBYID_IDS					= 'pp0011x02';		
	//FOLLOW THE USER BY TELEPHONE
	CONST PFOLLOWUSERBYTELEPHONE_USERID			= 'pp0036x01';
	CONST PFOLLOWUSERBYTELEPHONE_TELEPHONES		= 'pp0036x02';
	//UNFOLLOW USER BY ID
	CONST PUNFOLLOWUSERBYID_USERID				= 'pp0038x01';
	CONST PUNFOLLOWUSERBYID_IDS					= 'pp0038x02';
	//SET AVATAR OF USER
	CONST PSETAVATAR_USERID						= 'pp0012x01';
	CONST PSETAVATAR_AVATAR						= 'pp0012x02';
	//SET NEW PASSWORD	
	CONST PSETNEWPASSWORD_USERID				= 'pp0013x01';
	CONST PSETNEWPASSWORD_OLDPWD				= 'pp0013x02';
	CONST PSETNEWPASSWORD_NEWPWD				= 'pp0013x03';
	//SET SAYING
	CONST PSETSAYING_USERID						= 'pp0014x01';
	CONST PSETSAYING_SAYING						= 'pp0014x02';
	//ADD PLACE		
	CONST PADDPLACE_USERID						= 'pp0015x01';
	CONST PADDPLACE_NAME						= 'pp0015x02';
	CONST PADDPLACE_LONGITUDE					= 'pp0015x03';
	CONST PADDPLACE_LATITUDE					= 'pp0015x04';
	//DELETE PLACE
	CONST PDELETEPLACE_USERID					= 'pp0016x01';
	CONST PDELETEPLACE_PLACEID					= 'pp0016x02';
	//ADD INFO TO  JOURNAL PLACE
	CONST PADDJOURNALPLACEINFO_USERID			= 'pp0017x01';
	CONST PADDJOURNALPLACEINFO_JOURNALPLACEID	= 'pp0017x02';
	CONST PADDJOURNALPLACEINFO_INFOTEXT			= 'pp0017x03';
	CONST PADDJOURNALPLACEINFO_LATITUDE			= 'pp0017x04';
	CONST PADDJOURNALPLACEINFO_LONGITUDE		= 'pp0017x05';
	//ADD PHOTO TO JOURNAL INFO
	CONST PADDPHOTOTOJOURNALINFO_USERID			= 'pp0018x01';
	CONST PADDPHOTOTOJOURNALINFO_INFOID			= 'pp0018x02';
	CONST PADDPHOTOTOJOURNALINFO_PHOTOTITLE		= 'pp0018x03';
	CONST PADDPHOTOTOJOURNALINFO_PHOTO			= 'pp0018x04';
	//COMMENT THE JOURNAL
	CONST PCOMMENTJOURNAL_USERID				= 'pp0019x01';
	CONST PCOMMENTJOURNAL_JOURNALID				= 'pp0019x02';
	CONST PCOMMENTJOURNAL_COMMENT				= 'pp0019x03';
	//COMMENT THE JOURNAL PLACE
	CONST PCOMMENTJOURNALPLACE_USERID			= 'pp0020x01';
	CONST PCOMMENTJOURNALPLACE_JOURLANPLACEID	= 'pp0020x02';
	CONST PCOMMENTJOURNALPLACE_COMMENT			= 'pp0020x03';
	//CREATE A JOURNAL
	CONST PCREATEJOURNAL_USERID					= 'pp0021x01';
	CONST PCREATEJOURNAL_TITLE					= 'pp0021x02';
	CONST PCREATEJOURNAL_ISPRIVATE				= 'pp0021x03';
	//CREATE A JOURNAL PLACE
	CONST PCREATEJOURNALPLACE_USERID			= 'pp0022x01';
	CONST PCREATEJOURNALPLACE_PLACE				= 'pp0022x02';
	CONST PCREATEJOURNALPLACE_JOURNALID			= 'pp0022x03';
	CONST PCREATEJOURNALPLACE_LONGITUE			= 'pp0022x04';
	CONST PCREATEJOURNALPLACE_LATITUDE			= 'pp0022x05';
	//DELETE JOURNAL	
	CONST PDELETEJOURNAL_USERID					= 'pp0023x01';
	CONST PDELETEJOURNAL_JOURNALID				= 'pp0023x02';
	//DELETE JOURNAL PLACE
	CONST PDELETEJOURNALPLACE_USERID			= 'pp0024x01';
	CONST PDELETEJOURNALPLACE_JOURNALPLACEID	= 'pp0024x02';
	//DELETE JOURNAL PLACE INFO
	CONST PDELETEJOURNALPLACEINFO_USERID		= 'pp0041x01';
	CONST PDELETEJOURNALPLACEINFO_INFOID		= 'pp0041x02';
	//DELETE JOURNAL PLACE INFO PLACE
	CONST PDELETEINFOPHOTO_USERID				= 'pp0042x01';
	CONST PDELETEINFOPHOTO_PHOTOID				= 'pp0042x02';
	//DELETE JOURNAL COMMENT
	CONST PDELETEJOURNALCOMMENT_USERID			= 'pp0043x01';
	CONST PDELETEJOURNALCOMMENT_COMMENTID		= 'pp0043x02';
	//DELETE JOURNAL PLACE COMMENT
	CONST PDELETEJOURNALPLACECOMMENT_USERID		= 'pp0044x01';
	CONST PDELETEJOURNALPLACECOMMENT_COMMENTID	= 'pp0044x02';
	//FAVOURITE JOURNAL
	CONST PFAVOURITEJOURNAL_USERID				= 'pp0025x01';
	CONST PFAVOURITEJOURNAL_JOURNALID			= 'pp0025x02';
	CONST PFAVOURITEJOURNAL_COMMENT				= 'pp0025x03';
	//FAVOURITE JOURNAL PLACE
	CONST PFAVOURITEJOURNALPLACE_USERID			= 'pp0026x01';
	CONST PFAVOURITEJOURNALPLACE_JOURNALPLACEID	= 'pp0026x02';
	CONST PFAVOURITEJOURNALPLACE_COMMENT		= 'pp0026x03';
	//UNFAVOURITE JOURNAL
	CONST PUNFAVOURITEJOURNAL_USERID			= 'pp0039x01';
	CONST PUNFAVOURITEJOURNAL_JOURNALID			= 'pp0039x02';
	//UNFAVOURITE JOURNAL PLACE
	CONST PUNFAVOURITEJOURNALPLACE_USERID			= 'pp0040x01';
	CONST PUNFAVOURITEJOURNALPLACE_JOURNALPLACEID	= 'pp0040x02';
	//SET JOURNAL PRIVACY
	CONST PSETJOURNALPRIVACY_USERID				= 'pp0027x01';
	CONST PSETJOURNALPRIVACY_JOURNALID			= 'pp0027x02';
	CONST PSETJOURNALPRIVACY_ISPRIVATE			= 'pp0027x03';
	//ADD USER TO BLACKLIST
	CONST PADDBLACKLIST_USERID					= 'pp0028x01';
	CONST PADDBLACKLIST_BLACKLIST				= 'pp0028x01';
	//CLEAR BLACKLIST
	CONST PCLEARBLACKLIST_USERID				= 'pp0029x01';
	//DELETE USER ID FROM BLACKLIST
	CONST PDELETEBLACKLIST_USERID				= 'pp0030x01';
	CONST PDELETEBLACKLIST_BLACKLIST			= 'pp0030x02';
	//ENABLE IM
	CONST PENABLEIM_USERID						= 'pp0031x01';
	CONST PENABLEIM_ISENABLE					= 'pp0031x02';
	//RECEIVE MSG	
	CONST PRECEIVEMSG_USERID					= 'pp0032x01';
	//SEND MSG
	CONST PSENDMSG_USERID						= 'pp0033x01';
	CONST PSENDMSG_RECEIVEUSERID				= 'pp0033x02';
	CONST PSENDMSG_MSG							= 'pp0033x03';
	//ADD PLACE TAG
	CONST PADDPLACETAG_USERID					= 'pp0034x01';
	CONST PADDPLACETAG_PLACEID					= 'pp0034x02';
	CONST PADDPLACETAG_TAG						= 'pp0034x03';
	//AGREE TAG
	CONST PAGREETAG_USERID						= 'pp0035x01';
	CONST PAGREETAG_PLACETAGID					= 'pp0035x02';
	//...>>
	//behavior parameter end
	
	private static $propertys = array(
		self::BREGISTEREMAIL			=> array(
			self::PREGISTEREMAIL_EMAIL , 
			self::PREGISTEREMAIL_PASSWORD ,
			self::PREGISTEREMAIL_USERNAME	
		),
		self::BREGISTERTELEPHONE		=> array(
			self::PREGISTERTELEPHONE_TELEPHONE , 
			self::PREGISTERTELEPHONE_PASSWORD ,
			self::PREGISTERTELEPHONE_USERNAME
		),
		self::BREGISTEROTHERS			=> array(
			self::PREGISTEROTHERS_ACCESSTOKEN
		),
		self::BREGISTERCONFIRMEMAIL		=> array(
			self::PREGISTERCONFIRMEMAIL_VERIFYCODE
		),
		self::BREGISTERCONFIRMTELEPHONEBYMSG	=> array(
			self::PREGISTERCONFIRMTELEPHONEBYMSG_TELEPHONE , 
			self::PREGISTERCONFIRMTELEPHONEBYMSG_CONTENT		
		),
		self::BREGISTERCONFIRMTELEPHONEBYCODE	=> array(
			self::PREGISTERCONFIRMTELEPHONEBYCODE_VERIFYCODE
		),
		self::BLOGINEMAIL				=> array(
			self::PLOGINEMAIL_EMAIL , 
			self::PLOGINEMAIL_PASSWORD
		),
		self::BLOGINTELEPHONE			=> array(
			self::PLOGINTELEPHONE_TELEPHONE , 
			self::PLOGINTELEPHONE_PASSWORD
		),
		self::BLOGINOTHERS				=> array(

		),
		self::BBINDEMAIL				=> array(
			self::PBINDEMAIL_USERID , 
			self::PBINDEMAIL_EMAIL
		),	
		self::BBINDMOBILE				=> array(
			self::PBINDMOBILE_USERID , 
			self::PBINDMOBILE_MOBILE
		),
		self::BFOLLOWUSERBYID			=> array(
			self::PFOLLOWUSERBYID_USERID , 
			self::PFOLLOWUSERBYID_IDS
		),
		self::BFOLLOWUSERBYTELEPHONE	=> array(
			self::PFOLLOWUSERBYTELEPHONE_USERID , 
			self::PFOLLOWUSERBYTELEPHONE_TELEPHONES
		),
		self::BUNFOLLOWUSERBYID			=> array(
			self::PUNFOLLOWUSERBYID_USERID , 
			self::PUNFOLLOWUSERBYID_IDS
		),
		self::BSETAVATAR				=> array(
			self::PSETAVATAR_USERID , 
			self::PSETAVATAR_AVATAR
		),
		self::BSETNEWPASSWORD			=> array(
			self::PSETNEWPASSWORD_USERID , 
			self::PSETNEWPASSWORD_OLDPWD , 
			self::PSETNEWPASSWORD_NEWPWD
		),
		self::BSETSAYING				=> array(
			self::PSETSAYING_USERID , 
			self::PSETSAYING_SAYING
		),
		self::BADDPLACE					=> array(
			self::PADDPLACE_USERID , 
			self::PADDPLACE_NAME , 
			self::PADDPLACE_LONGITUDE , 
			self::PADDPLACE_LATITUDE
		),
		self::BDELETEPLACE				=> array(
			self::PDELETEPLACE_USERID , 
			self::PDELETEPLACE_PLACEID
		),
		self::BADDJOURNALPLACEINFO 		=> array(
			self::PADDJOURNALPLACEINFO_USERID ,
			self::PADDJOURNALPLACEINFO_JOURNALPLACEID , 
			self::PADDJOURNALPLACEINFO_INFOTEXT,
			self::PADDJOURNALPLACEINFO_LATITUDE , 
			self::PADDJOURNALPLACEINFO_LONGITUDE
		),
		self::BADDPHOTOTOJOURNALINFO	=> array(
			self::PADDPHOTOTOJOURNALINFO_USERID , 
			self::PADDPHOTOTOJOURNALINFO_INFOID , 
			self::PADDPHOTOTOJOURNALINFO_PHOTOTITLE , 
			self::PADDPHOTOTOJOURNALINFO_PHOTO
		),
		self::BCOMMENTJOURNAL			=> array(
			self::PCOMMENTJOURNAL_USERID , 
			self::PCOMMENTJOURNAL_JOURNALID , 
			self::PCOMMENTJOURNAL_COMMENT
		),
		self::BCOMMENTJOURNALPLACE		=> array(
			self::PCOMMENTJOURNALPLACE_USERID , 
			self::PCOMMENTJOURNALPLACE_JOURLANPLACEID , 
			self::PCOMMENTJOURNALPLACE_COMMENT
		),
		self::BCREATEJOURNAL			=> array(
			self::PCREATEJOURNAL_USERID , 
			self::PCREATEJOURNAL_TITLE , 
			self::PCREATEJOURNAL_ISPRIVATE
		),
		self::BCREATEJOURNALPLACE		=> array(
			self::PCREATEJOURNALPLACE_USERID , 
			self::PCREATEJOURNALPLACE_JOURNALID , 
			self::PCREATEJOURNALPLACE_PLACE , 
			self::PCREATEJOURNALPLACE_LONGITUE , 
			self::PCREATEJOURNALPLACE_LATITUDE
		),
		self::BDELETEJOURNAL			=> array(
			self::PDELETEJOURNAL_USERID , 
			self::PDELETEJOURNAL_JOURNALID
		),
		self::BDELETEJOURNALPLACE		=> array(
			self::PDELETEJOURNALPLACE_USERID , 
			self::PDELETEJOURNALPLACE_JOURNALPLACEID
		),
		self::BDELETEJOURNALPLACEINFO	=>array(
			self::PDELETEJOURNALPLACEINFO_USERID , 
			self::PDELETEJOURNALPLACEINFO_INFOID
		),
		self::BDELETEINFOPHOTO			=> array(
			self::PDELETEINFOPHOTO_USERID , 
			self::PDELETEINFOPHOTO_PHOTOID
		),
		self::BDELETEJOURNALCOMMENT		=> array(
			self::PDELETEJOURNALCOMMENT_USERID , 
			self::PDELETEJOURNALCOMMENT_COMMENTID
		),
		self::BDELETEJOURNALPLACECOMMENT=> array(
			self::PDELETEJOURNALPLACECOMMENT_USERID ,
			self::PDELETEJOURNALPLACECOMMENT_COMMENTID 
		),
		self::BFAVOURITEJOURNAL			=> array(
			self::PFAVOURITEJOURNAL_USERID , 
			self::PFAVOURITEJOURNAL_JOURNALID,
			self::PFAVOURITEJOURNAL_COMMENT
		),
		self::BFAVOURITEJOURNALPLACE	=> array(
			self::PFAVOURITEJOURNALPLACE_USERID , 
			self::PFAVOURITEJOURNALPLACE_JOURNALPLACEID,
			self::PFAVOURITEJOURNALPLACE_COMMENT
		),
		self::BUNFAVOURITEJOURNAL		=> array(
			self::PUNFAVOURITEJOURNAL_USERID , 
			self::PUNFAVOURITEJOURNAL_JOURNALID
		),
		self::BUNFAVOURITEJOURNALPLACE	=> array(
			self::PUNFAVOURITEJOURNALPLACE_USERID , 
			self::PUNFAVOURITEJOURNALPLACE_JOURNALPLACEID
		),
		self::BSETJOURNALPRIVACY		=> array(
			self::PSETJOURNALPRIVACY_USERID , 
			self::PSETJOURNALPRIVACY_JOURNALID , 
			self::PSETJOURNALPRIVACY_ISPRIVATE
		),
		self::BADDBLACKLIST				=> array(
			self::PADDBLACKLIST_USERID , 
			self::PADDBLACKLIST_BLACKLIST
		),
		self::BCLEARBLACKLIST			=> array(
			self::PCLEARBLACKLIST_USERID
		),
		self::BDELETEBLACKLIST			=> array(
			self::PDELETEBLACKLIST_USERID , 
			self::PDELETEBLACKLIST_BLACKLIST
		),
		self::BENABLEIM					=> array(
			self::PENABLEIM_USERID , 
			self::PENABLEIM_ISENABLE
		),
		self::BRECEIVEMSG				=> array(
			self::PRECEIVEMSG_USERID
		),
		self::BSENDMSG					=> array(
			self::PSENDMSG_USERID , 
			self::PSENDMSG_RECEIVEUSERID , 
			self::PSENDMSG_MSG
		),
		self::BADDPLACETAG				=> array(
			self::PADDPLACETAG_USERID,
			self::PADDPLACETAG_PLACEID,
			self::PADDPLACETAG_TAG
		),
		self::BAGREETAG					=> array(
			self::PAGREETAG_USERID,
			self::PAGREETAG_PLACETAGID
		)
	);
	private static $names = array(
		self::BREGISTEREMAIL 			=> 'User_PRegisterEmail',
		self::BREGISTERTELEPHONE		=> 'User_PRegisterTelephone',
		self::BREGISTEROTHERS			=> 'User_PRegisterOthers',
		self::BREGISTERCONFIRMEMAIL		=> 'User_PRegisterConfirmEmail',
		self::BREGISTERCONFIRMTELEPHONEBYMSG	=> 'User_PRegisterConfirmTelephoneByMsg',
		self::BREGISTERCONFIRMTELEPHONEBYCODE	=> 'User_PRegisterConfirmTelephoneByCode',
		self::BLOGINEMAIL				=> 'User_PLoginEmail',
		self::BLOGINTELEPHONE			=> 'User_PLoginTelephone',
		self::BLOGINOTHERS				=> 'User_PLoginOthers',
		self::BBINDEMAIL				=> 'User_PBindEmail',
		self::BBINDMOBILE				=> 'User_PBindMobile',
		self::BFOLLOWUSERBYID			=> 'User_PFollowUserById',
		self::BFOLLOWUSERBYTELEPHONE	=> 'User_PFollowUserByTelephone',
		self::BUNFOLLOWUSERBYID			=> 'User_PUnFollowUserById',
		self::BSETAVATAR				=> 'User_PSetAvatar',
		self::BSETNEWPASSWORD			=> 'User_PSetNewPassword',
		self::BSETSAYING				=> 'User_PSetSaying',
		self::BADDPLACE					=> 'Geographic_PAddPlace',
		self::BDELETEPLACE				=> 'Geographic_PDeletePlace',
		self::BADDJOURNALPLACEINFO		=> 'Journal_PAddJournalPlaceInfo',
		self::BADDPHOTOTOJOURNALINFO	=> 'Journal_PAddPhotoToJournalInfo',
		self::BCOMMENTJOURNAL			=> 'Journal_PCommentJournal',
		self::BCOMMENTJOURNALPLACE		=> 'Journal_PCommentJournalPlace',
		self::BCREATEJOURNAL			=> 'Journal_PCreateJournal',
		self::BCREATEJOURNALPLACE		=> 'Journal_PCreateJournalPlace',
		self::BDELETEJOURNAL			=> 'Journal_PDeleteJournal',
		self::BDELETEJOURNALPLACE		=> 'Journal_PDeleteJournalPlace',
		self::BDELETEJOURNALPLACEINFO	=> 'Journal_PDeleteJournalPlaceInfo',
		self::BDELETEINFOPHOTO			=> 'Journal_PDeleteInfoPhoto', 
		self::BDELETEJOURNALCOMMENT		=> 'Journal_PDeleteJournalComment', 
		self::BDELETEJOURNALPLACECOMMENT=> 'Journal_PDeleteJournalPlaceComment',
		self::BFAVOURITEJOURNAL			=> 'Journal_PFavouriteJournal',
		self::BFAVOURITEJOURNALPLACE	=> 'Journal_PFavouriteJournalPlace',
		self::BUNFAVOURITEJOURNAL		=> 'Journal_PUnFavouriteJournal',
		self::BUNFAVOURITEJOURNALPLACE	=> 'Journal_PUnFavouriteJournalPlace',
		self::BSETJOURNALPRIVACY		=> 'Journal_PSetJournalPrivacy',
		self::BADDBLACKLIST				=> 'Im_PAddBlackList',
		self::BCLEARBLACKLIST			=> 'Im_PClearBlackList',
		self::BDELETEBLACKLIST			=> 'Im_PDeleteBlackList',
		self::BENABLEIM					=> 'Im_PEnableIm',
		self::BRECEIVEMSG				=> 'Im_PReceiveMsg',
		self::BSENDMSG					=> 'Im_PSendMsg',
		self::BADDPLACETAG				=> 'Geographic_PAddPlaceTag',
		self::BAGREETAG					=> 'Geographic_PAgreeTag',	
	);
	private static $lines = array(
		self::BREGISTEREMAIL => array(
		
		),
	);
	
	/**
	 * 
	 * get all property ids of a behavior
	 * @param string $behaviorId
	 */
	public static function getPropertyIds($behaviorId)
	{
		return self::$propertys[$behaviorId];
	}
	/**
	 * 
	 * get name of a behavior
	 * @param string $behaviorId
	 */
	public static function getName($behaviorId)
	{
		if (array_key_exists($behaviorId, self::$names))
		{
			return self::COMMONBHNAME . self::$names[$behaviorId];			
		}
		else
		{
			return null;
		}	

	}
	public static function getAllNames()
	{
		$allNames = null;
		foreach (self::$names as $id => $name)
		{
			$allNames[$id] = self::COMMONBHNAME . $name;
		}
		return $allNames;
	}
	/**
	 * 
	 * get id of behavior lines
	 * @param string $behaviorId
	 */
	public static function getLineIds($behaviorId)
	{
		if (array_key_exists($behaviorId, self::$lines))
		{
			return self::$lines[$behaviorId];
		}
		else
		{
			return null;
		}	
	}
}